project:
  type: website
  output-dir: docs

website:
  title: "Job Market Analysis 2024"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: research_introduction.qmd
        text: "Research"
      - href: data_analysis.qmd
        text: "Data Analysis"
      - href: eda.qmd
        text: "Exploratory Data Analysis"
      - href: skill_gap_analysis.qmd
        text: "Skill-Gap Analysis" 
      - href: salary_trend_analysis.qmd
        text: "Final_Salary Trend Analysis" 
      - href: final_report.qmd
        text: "Report" 
format:
  html:
    theme: cosmo
    toc: true
execute:
  echo: true
  eval: true
  code-fold: true